name: Object Detection in Video

on:
  push:
    paths:
      - 'video.mp4'
  workflow_dispatch:

jobs:
  detect_objects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch torchvision torchaudio
          pip install opencv-python
          pip install git+https://github.com/ultralytics/yolov5.git

      - name: Run object detection
        run: |
          mkdir -p results
          python detect_objects.py > results/output.txt
          cat results/output.txt

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: detection-results
          path: results/output.txt
