name: YOLOv8 Video Detection

on:
  push:
    paths:
      - '**.mp4'
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install ultralytics opencv-python

    - name: Process all MP4s with YOLOv8
      run: |
        python - <<EOF
        import cv2
        from ultralytics import YOLO
        from glob import glob
        import os

        model = YOLO('yolov8n.pt')
        for path in glob("*.mp4"):
            cap = cv2.VideoCapture(path)
            w, h = int(cap.get(3)), int(cap.get(4))
            fps = cap.get(cv2.CAP_PROP_FPS)
            out_path = f"out_{os.path.basename(path)}"
            out = cv2.VideoWriter(out_path, cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))
            while cap.isOpened():
                ret, frame = cap.read()
                if not ret: break
                results = model(frame)[0]
                for box in results.boxes:
                    x1, y1, x2, y2 = map(int, box.xyxy[0])
                    label = model.names[int(box.cls[0])]
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                    cv2.putText(frame, label, (x1, y1-5), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0,255,0), 1)
                out.write(frame)
            cap.release()
            out.release()
        EOF

    - name: Upload processed videos
      uses: actions/upload-artifact@v4
      with:
        name: yolo-videos
        path: out_*.mp4
